In [1]:
# Import the libraries

import pandas as pd
import seaborn as sns

In [2]:
# Load the dataset

df = pd.read_csv('../data/rating.csv')

df.columns

Index(['article_id', 'source_id', 'source_name', 'author', 'title',
       'description', 'url', 'url_to_image', 'published_at', 'content',
       'category', 'article', 'title_sentiment'],
      dtype='object')

In [3]:
# Quick overview of Data

df.head()

,article_id,source_id,source_name,author,title,description,url,url_to_image,published_at,content,category,article,title_sentiment
0,81664,NaN,Forbes,"Elizabeth Brownfield, Contributor, \n Elizabet...",superstar chef yannick alléno brings refined f...,Now open in Mayfair at Four Seasons Hotel Lond...,https://www.forbes.com/sites/elizabethbrownfie...,https://imageio.forbes.com/specials-images/ima...,2023-11-01 03:27:21.000000,"Pavyllon London, at Four Seasons Hotel London ...",Monaco,"pavyllon london, at four seasons hotel london ...",Neutral
1,81667,NaN,CNA,NaN,nice claim top spot in ligue 1 with late win a...,Nice moved into provisional first place in the...,https://www.channelnewsasia.com/sport/nice-cla...,https://onecms-res.cloudinary.com/image/upload...,2023-10-27 21:28:48.000000,Nice moved into provisional first place in the...,Monaco,nice moved into provisional first place in the...,Positive
2,81694,time,Time,Christina Larson / AP,amphibians are the world’s most vulnerable spe...,"The world’s frogs, salamanders, newts, and oth...",https://time.com/6320467/amphibians-most-vulne...,https://api.time.com/wp-content/uploads/2023/1...,2023-10-04 17:36:18.000000,"The worlds frogs, salamanders, newts and other...",Madagascar,"the world’s frogs, salamanders, newts and othe...",Negative
3,81695,NaN,Phys.Org,Sara Schmidt,image: rusty red waters in madagascar,Iron-rich sediment colors the red-orange water...,https://phys.org/news/2023-10-image-rusty-red-...,https://scx2.b-cdn.net/gfx/news/2023/image-rus...,2023-10-31 18:04:02.000000,Iron-rich sediment colors the red-orange water...,Madagascar,iron-rich sediment colors the red-orange water...,Neutral
4,81703,NaN,Digital Trends,Jason Struss,everything leaving max (formerly hbo max) in n...,From Gangs of London to Fear the Walking Dead ...,https://www.digitaltrends.com/movies/everythin...,https://www.digitaltrends.com/wp-content/uploa...,2023-10-23 23:09:18.000000,"Everything ends. No, I’m not having an existen...",Madagascar,"everything ends. no, i’m not having an existen...",Neutral

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58356 entries, 0 to 58355
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   article_id       58356 non-null  int64
 1   source_id        17771 non-null  object
 2   source_name      58356 non-null  object
 3   author           56193 non-null  object
 4   title            58356 non-null  object
 5   description      58346 non-null  object
 6   url              58356 non-null  object
 7   url_to_image     54905 non-null  object
 8   published_at     58356 non-null  object
 9   content          58356 non-null  object
 10  category         58335 non-null  object
 11  article          58356 non-null  object
 12  title_sentiment  58356 non-null  object
dtypes: int64(1), object(12)
memory usage: 5.8+ MB

In [6]:
df.isnull().sum()

article_id             0
source_id          40585
source_name            0
author              2163
title                  0
description           10
url                    0
url_to_image        3451
published_at           0
content                0
category              21
article                0
title_sentiment        0
dtype: int64

In [7]:
# Exploring the categories

df['category'].unique()

array(['Monaco', 'Madagascar', 'Mexico', 'Maldives', 'Mali', 'Barbados',
       'Nicaragua', 'Congo, The Democratic Republic of the',
       'North Macedonia', 'Malta', 'Poland', 'Myanmar',
       'Russian Federation', 'Mongolia', 'Montenegro', 'Malaysia',
       'Romania', 'Mozambique', 'Montserrat', 'South Sudan', 'News',
       'Israel', 'Mauritania', 'Mauritius', 'Netherlands', 'Martinique',
       'Malawi', 'Germany', 'Niger', 'Namibia', 'Nigeria', 'Georgia',
       'Nepal', 'Facebook', 'Norway', 'COVID', 'Peru', 'Travel',
       'History', 'Papua New Guinea', 'New Zealand', 'Sports', 'Oman',
       'Pakistan', 'Panama', 'Love', 'America', 'Philippines', 'Palau',
       'Politics', 'Armenia', 'Food', 'Sudan', 'Puerto Rico', 'Weather',
       'Real estate', 'Cars', 'Senegal', 'Singapore', 'Stock', 'Ghana',
       'TikTok', 'Photography', 'Kazakhstan', 'Games', 'Climate', 'Space',
       'Somalia', 'Tonga', 'Architecture', 'Art', 'Africa',
       'Relationships', 'Qatar', 'world', 'Beauty', 'Podcasts', 'Yoga',
       'Coding', 'Cryptocurrency', 'Nutrition', 'Design',
       'Sustainability', 'Blockchain', 'Startups',
       'Artificial Intelligence', 'Motivation', 'Hiking', 'Productivity',
       'Health', 'Philosophy', 'Europe', 'Serbia', 'Google', 'YouTube',
       'Amazon', 'Jobs', 'Movies', 'Music', 'Technology', 'Sweden',
       'Bitcoin', 'Finance', 'Fashion', 'Instagram', 'Fitness', 'Science',
       'Education', 'Home', nan, 'Asia', 'Portugal', 'Paraguay', 'Pets',
       'Palestine, State of', 'Rwanda', 'Saudi Arabia', 'Sierra Leone',
       'El Salvador', 'San Marino', 'Suriname', 'Slovakia', 'Ukraine',
       'Slovenia', 'Seychelles', 'Tunisia', 'United States', 'Turkey',
       'Taiwan, Province of China', 'Uganda', 'Uruguay', 'Uzbekistan',
       'Yemen', 'Samoa', 'Virgin Islands, U.S.', 'Viet Nam', 'Vanuatu',
       'South Africa', 'Zambia', 'Zimbabwe', 'Thailand', 'Tajikistan',
       'Chad', 'Turkmenistan', 'Recipes', 'Austria', 'DIY', 'Psychology',
       'Virtual Reality', 'Australia', 'Meditation', 'Gardening', 'Vegan',
       'Parenting', 'Anime', 'Mindfulness', 'Bangladesh', 'Djibouti',
       'Entrepreneurship', 'Azerbaijan', 'Belarus', 'Lithuania', 'Poetry',
       'Happiness', 'Canada', 'Minimalism', 'Astronomy', 'Guam',
       'Afghanistan', 'Aruba', 'United Arab Emirates', 'Angola',
       'Andorra', 'Albania', 'Hungary', 'Guernsey', 'Antarctica',
       'Argentina', 'Switzerland', 'Haiti', 'Burundi', 'Belgium', 'China',
       'Benin', 'Iraq', 'Burkina Faso', 'Latvia', 'Bulgaria', 'Bahrain',
       'Bahamas', 'Bosnia and Herzegovina', 'Botswana', 'Belize',
       'Brazil', 'Bermuda', 'Central African Republic', 'Cyprus',
       'Bhutan', 'Chile', "Côte d'Ivoire", 'Cameroon', 'Congo',
       'Colombia', 'Christmas Island', 'Cabo Verde', 'Costa Rica', 'Cuba',
       'Cayman Islands', 'Denmark', 'Egypt', 'Dominican Republic',
       'Kenya', 'Algeria', 'Eritrea', 'Ecuador', 'Iceland', 'Spain',
       'Estonia', 'Ethiopia', 'Finland', 'Fiji', 'France', 'Gabon',
       'Cambodia', 'Libya', 'United Kingdom', 'Gibraltar', 'Guinea',
       'Gambia', 'Greece', 'Iran, Islamic Republic of', 'Guatemala',
       'Greenland', 'India', 'Guyana', 'Hong Kong', 'Luxembourg',
       'Honduras', 'Croatia', 'Indonesia', 'Isle of Man', 'Ireland',
       'Jersey', 'Italy', 'Jamaica', 'Jordan', 'Kyrgyzstan', 'Japan',
       'Korea, Republic of', 'Lebanon', 'Kuwait', 'Liberia',
       'Liechtenstein', 'Sri Lanka', 'Morocco', 'Macao', 'Réunion'],
      dtype=object)

In [ ]:
df['category'].value_counts()